name: Publish
on:
  push:
    paths:
      - 'extension.js'
      - 'package.json'
      - 'package-lock.json'

jobs:
  PackageAndPublish:
    runs-on: ubuntu-latest
    steps:
      - run: npm install -g vsce
      - run: vsce package
      - run: vsce publish
